# Generated by Django 4.0.6 on 2022-07-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
